DROP TABLE IF EXISTS student;
CREATE TABLE student (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(200) UNIQUE NOT NULL,
	study_group_id INTEGER,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(study_group_id) REFERENCES study_group (id)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);
DROP TABLE IF EXISTS study_group;
CREATE TABLE study_group (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	group_name VARCHAR(50) UNIQUE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS teacher;
CREATE TABLE teacher (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(200) UNIQUE NOT NULL,
	is_sciens_title BOOLEAN,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS stady_subject;
CREATE TABLE stady_subject (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	subject_name VARCHAR(200) UNIQUE NOT NULL,
	teacher_id INTEGER,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(teacher_id) REFERENCES teacher (id)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);
DROP TABLE IF EXISTS evaluation;
CREATE TABLE evaluation (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	student_id INTEGER,
	subject_id INTEGER,
	evalution_val INTEGER,
	created_at DATE NOT NULL,
	FOREIGN KEY(student_id) REFERENCES student (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(subject_id) REFERENCES stady_subject (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);